### ISSUE TITLE
Undefined Method 'warning' 

### ISSUE THREAD

**Issue by dizzy721** [merefield/discourse-onebox-assistant#2]
https://github.com/merefield/discourse-onebox-assistant/blob/8944e8d20b8c8d6825af3f6eeb8fb1973a13d528/plugin.rb#L114

> Started GET "/onebox?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DPPSp8sJsbmM&refresh=false&category_id=1&topic_id=33" for [IP REMOVED] at 2021-01-17 20:44:24 +0000
> Processing by OneboxController#show as HTML
>   Parameters: {"url"=>"https://www.youtube.com/watch?v=PPSp8sJsbmM", "refresh"=>"false", "category_id"=>"1", "topic_id"=>"33"}
>   Rendering text template
>   Rendered text template (Duration: 0.0ms | Allocations: 1)
> Completed 418  in 27ms (Views: 2.0ms | ActiveRecord: 0.0ms | Allocations: 5487)
> ONEBOX ASSIST: the url being sought from API is https://www.youtube.com/watch?v=PPSp8sJsbmM
> Failed to onebox https://www.youtube.com/watch?v=PPSp8sJsbmM undefined method 'warning' for #<Logster::Logger:0x00007f0925c0a988>
> Did you mean?  warn ["/var/www/discourse/plugins/discourse-onebox-assistant/plugin.rb:114:in 'fetch_html_doc'", "/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/onebox-2.2.1/lib/onebox/engine/standard_embed.rb:75:in 'html_doc'", "/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/onebox-2.2.1/lib/onebox/engine/standard_embed.rb:83:in 'get_opengraph'", "/var/www/discourse/plugins/lazy-yt/plugin.rb:31:in 'to_html'", "/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/onebox-2.2.1/lib/onebox/preview.rb:51:in 'engine_html'", "/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/onebox-2.2.1/lib/onebox/preview.rb:22:in 'to_s'", "/var/www/discourse/plugins/discourse-onebox-assistant/plugin.rb:60:in 'block in external_onebox'", "/var/www/discourse/lib/cache.rb:94:in 'fetch'", "/var/www/discourse/plugins/discourse-onebox-assistant/plugin.rb:18:in 'external_onebox'", "/var/www/discourse/lib/oneboxer.rb:199:in 'onebox_raw'", "/var/www/discourse/lib/oneboxer.rb:44:in 'preview'", "/var/www/discourse/app/controllers/onebox_controller.rb:27:in 'block in show'", "/var/www/discourse/lib/hijack.rb:56:in 'instance_eval'", "/var/www/discourse/lib/hijack.rb:56:in 'block in hijack'", "/var/www/discourse/lib/scheduler/defer.rb:94:in 'block in do_work'", "/var/www/discourse/vendor/bundle/ruby/2.7.0/gems/rails_multisite-2.5.0/lib/rails_multisite/connection_management.rb:76:in 'with_connection'", "/var/www/discourse/lib/scheduler/defer.rb:89:in 'do_work'", "/var/www/discourse/lib/scheduler/defer.rb:79:in 'block (2 levels) in start_thread'"]

Experiencing an issue with Oneboxing all URLs on our Discourse. I think the root cause is an issue with embed.rocks where we are getting a 418 Response which is pretty weird.  However, the plugin code tries to print the error to Rails.logger.warning which throws the above undefined method error. This should probably be [Rails.logger.warn](https://ruby-doc.org/stdlib-2.7.0/libdoc/logger/rdoc/Logger.html), no?

**Comment by merefield** [comment]
@dizzy721 

yes, that's correct and was corrected a while back.  Profuse apologies for the late response!

Closing this issue.
